---
permalink: performance-checker/concept_um_interfaces_used_to_manage_storage_system_performance.html 
sidebar: sidebar 
keywords: unified manager, interfaces, used, manage, storage, system, performance, web ui, maintenance, console 
summary: 'Há duas interfaces de usuário fornecidas pelo Active IQ Unified Manager para monitorar e solucionar problemas de performance de storage de dados: A interface de usuário da Web e o console de manutenção.' 
---
= Interfaces do Unified Manager usadas para gerenciar a performance do sistema de storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Há duas interfaces de usuário fornecidas pelo Active IQ Unified Manager para monitorar e solucionar problemas de performance de storage de dados: A interface de usuário da Web e o console de manutenção.



== IU da Web do Unified Manager

A IU da Web do Unified Manager permite que um administrador monitore e solucione problemas no sistema de storage relacionados ao desempenho.

Essas seções descrevem alguns fluxos de trabalho comuns que um administrador pode seguir para solucionar problemas de desempenho de storage exibidos na IU da Web do Unified Manager.



== Consola de manutenção

O console de manutenção permite que um administrador monitore, diagnostique e solucione problemas do sistema operacional, problemas de atualização de versão, problemas de acesso do usuário e problemas de rede relacionados ao próprio servidor do Unified Manager. Se a IU da Web do Unified Manager não estiver disponível, o console de manutenção será a única forma de acesso ao Unified Manager.

Essas seções fornecem instruções para acessar o console de manutenção e usá-lo para resolver problemas relacionados ao funcionamento do servidor do Unified Manager.
