---
permalink: health-checker/task_view_detailed_security_status_for_clusters_and_svms.html 
sidebar: sidebar 
keywords: view, cluster security status, svm security status, volume encryption status 
summary: A página Segurança mostra o status de segurança de alto nível para todos os clusters e o status de segurança detalhado para clusters individuais. O status detalhado do cluster inclui conformidade de cluster, conformidade com SVM e conformidade de criptografia de volumes. 
---
= Visualização do status de segurança detalhado dos clusters e das VMs de storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A página Segurança mostra o status de segurança de alto nível para todos os clusters e o status de segurança detalhado para clusters individuais.

Como administrador de sistema, você pode usar a página *Segurança* para obter visibilidade da força de segurança dos clusters do ONTAP e das VMs de armazenamento nos níveis do datacenter e do site.

Com base nos parâmetros definidos, você pode coletar e analisar informações para detetar comportamentos suspeitos ou alterações não autorizadas no sistema nos clusters monitorados e nas VMs de storage.

O status detalhado do cluster inclui conformidade de cluster, conformidade com SVM e conformidade de criptografia de volumes.

A página de detalhes de Cluster / Segurança fornece uma visualização padrão da conformidade de segurança dos clusters, verificando os parâmetros de segurança, como FIPS global, Telnet, configurações de SSH inseguras, banner de login, protocolo de tempo de rede, Transporte HTTPS AutoSupport e Administradores padrão.

A página Storage VMs/ Security details (Detalhes de Segurança/VMs de armazenamento) fornece uma visualização padrão da conformidade de segurança das VMs de armazenamento, verificando os parâmetros de segurança, como VMs de armazenamento, cluster, banner de login, log de auditoria e configurações inseguras de SSH.

Você também pode gerar, agendar e baixar relatórios de conformidade de segurança nas páginas de detalhes de VMs de Cluster e Storage.

No *Painel de Segurança*, clique em *Exibir relatórios* nas placas *conformidade de cluster* e *conformidade de VMs de armazenamento*.

.Passos
. No painel de navegação esquerdo, clique em *Dashboard*.
. Dependendo se você deseja exibir o status de segurança para todos os clusters monitorados ou para um único cluster, selecione *todos os clusters* ou selecione um único cluster no menu suspenso.
. Clique na seta para a direita no painel *Segurança*.
+
A página Segurança exibe as seguintes informações:

+
** o status de segurança do cluster (número de clusters que estão em conformidade ou não estão em conformidade)
** O status de segurança da SVM (número de SVMs em conformidade ou não em conformidade)
** o status da criptografia de volume (número de volumes criptografados ou não criptografados)
** os métodos de autenticação de cluster que estão sendo usados em cada cluster


. Consulte o https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf["Guia de endurecimento de segurança da NetApp para ONTAP 9"^] para obter instruções sobre como tornar todos os clusters, SVMs e volumes compatíveis com as recomendações de segurança da NetApp.

