---
permalink: events/task_upload_new_active_iq_rules_file.html 
sidebar: sidebar 
keywords: upload, new, active iq, rules, file 
summary: O Unified Manager verifica automaticamente um novo arquivo de regras do Active IQ e faz o download de um novo arquivo quando há regras mais recentes. No entanto, em sites sem acesso à rede externa, você precisa fazer o upload do arquivo de regras manualmente. 
---
= Carregar um novo ficheiro de regras do Active IQ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Unified Manager verifica automaticamente um novo arquivo de regras do Active IQ e faz o download de um novo arquivo quando há regras mais recentes. No entanto, em sites sem acesso à rede externa, você precisa fazer o upload do arquivo de regras manualmente.

*O que você vai precisar*

* O relatório de eventos do Active IQ deve estar ativado.
* Você deve baixar o arquivo de regras do site de suporte da NetApp.


Recomenda-se que faça o download de um novo arquivo de regras aproximadamente uma vez por mês para garantir que seus sistemas de storage estejam sendo protegidos e que eles estejam sendo executados de maneira ideal. O arquivo de regras está localizado em: http://mysupport.netapp.com/NOW/public/unified_manager/bin/secure_rules.zip[]

.Passos
. Em um computador com acesso à rede, navegue até o site de suporte da NetApp e baixe o arquivo de regras atual `.zip`.
. Transfira o ficheiro de regras para alguns suportes que pode introduzir na área segura e, em seguida, copie-o para um sistema na área segura.
. No painel de navegação à esquerda, clique em *Gerenciamento de armazenamento* > *Configuração do evento*.
. Na página *Configuração do evento*, clique no botão *Upload Rules*.
. Na caixa de diálogo *Upload Rules*, navegue e selecione o arquivo de regras `.zip` que você baixou e clique em *Upload*.
+
Este processo pode demorar alguns minutos.



O arquivo de regras é descompactado no servidor do Unified Manager. Depois que os clusters gerenciados geram um arquivo AutoSupport após a meia-noite, o Unified Manager verificará os clusters em relação ao arquivo de regras e gerará novos eventos de risco e incidente, se necessário.

Para obter mais informações, consulte este artigo da base de dados de Conhecimento (KB)link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/How_to_update_AIQCASecure_rules_manually_in_Active_IQ_Unified_Manager["Como atualizar as regras AIQCASecure manualmente no Active IQ Unified Manager"^]: .
